### ISSUE TITLE
Uploading File on nullable column

### ISSUE THREAD

**Issue by danielec** [padosoft/laravel-uploadable#3]
Hi,
I've noticed that if you update a Model uploading a file on a column that have null value, the function on row 626

`public function checkIfNeedToDeleteOldFile(string $uploadField) `

will throw an error on

`FileHelper::unlinkSafe(DirHelper::njoin($this->getUploadFileBasePath($uploadField), $oldValue)); `

row.

this is because the `$oldValue` variable is null.

I've patched the function adding the check 

`|| empty($this->getOriginal($uploadField)) `

in the first if of the function.

Hope this help!
Daniele

**Comment by lopadova** [comment]
FIX in v2.0.2
Thanks!
